# Generated by Django 3.2.16 on 2023-02-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
    ]
